### ISSUE TITLE
MASP parameters should be specified in the genesis file

### ISSUE THREAD

**Issue by james-chf** [anoma/anoma#1055]
We should include details of MASP parameter files in the network config file, and also the genesis file that is generated from that, similar to how include details of some WASMs.

e.g.
```toml
[masp_params.output]
filename = "masp-output.params"
sha256 = "8c9bb99a9eb45bdb62cda38b2d09b45eda22138910db5b194aa8c1ba1fdfda78"  # hash

# ...
```

These MASP params will be stored in a `masp/` directory in the chain directory.
```
Permissions Size User Date Modified Name
drwxr-xr-x     - main 13 Apr 14:48  .anoma
drwxr-xr-x     - main 13 Apr 14:49  ├── anoma-masp-0.3.51d2f83a8412b95
drwxr-xr-x     - main 13 Apr 14:49  │  ├── masp
.rw-r--r--   15M main 24 Mar 08:25  │  │  ├── masp-output.params
.rw-r--r--   48M main 24 Mar 08:25  │  │  └── masp-spend.params
```
